### PR TITLE
query-replace and clone operators

### PR DESCRIPTION
**Pull request by talwrii**

### CODE REVIEW

**Comment by Dewdrops** [comment]
Thanks for your PR. I agree that the bindings should be defined by user themselves. In fact I think the current documented way of binding (through minor mode, introducing all keybindings at once) is a design mistake.

I like the idea of the proposed new operators, but here are some thinks :
1. We should use some evil-specific interactive form (`<R>` or `<r>`) to let the operator behave consistently in both visual-state and normal-state. Detailed information can be found in `evil-types.el` of the evil package.
2. Autoload definition should be added to each operator to make them available via melpa or something similar.
3. Maybe a `:move-point nil` declaration can be added to keep from cursor moving away.
4. Current implementation of `evil-operator-clone` alway open a new line before the region. I think we can   just copy the text and insert them before the region (not always open a new line), and let the user choose the exact behaviour they want (a linewise text object will partly mimic current behaviour).

When we reach an agreement and make the work done, I'll merge them to master branch.

**Comment by talwrii** [comment]
> 1. We should use some evil-specific interactive form (<R> or <r>) to let the operator behave consistently in both visual-state and normal-state. Detailed information can be found in evil-types.el of the evil package.

Seems reasonable. I've lazily chosen to ignore block types and used <r>

> 2. Autoload definition should be added to each operator to make them available when installed via melpa or something similar.

Done

> 3. Maybe a :move-point nil declaration can be added to keep from cursor moving away.

Done. Less code than a `save-excursion`

> 4. Current implementation of evil-operator-clone alway open a new line before the region. I think we can just copy the text and insert them before the region (not always open a new line), and let the user choose the exact behaviour they want (a linewise text object will partly mimic current behaviour).

I'm not sure what the best option. I feel as if this might be a "do what I mean" command rather than a "provide me with an easy to understand conceptual model" command, so maybe be just have a bundle of edge cases!

Things that we want

1. CLONE iw - add a preceding space
1. CLONE ip - do not add whitespace lines
1. CLONE ap - add some sort of separating whitespace (following or preceding)
1. CLONE i( - should add a preceding space or newline depending on whether spans one ore more line. I specifically want to be able to clone defuns in list

The behaviour I've gone for is to ensure that when cloning multiple lines we have a newline at the end of the inserted string (adding one if necessary)

**Comment by Dewdrops** [comment]
It seems the DWIM version of `evil-operator-clone` works great for me. I also think there are too many edge cases to make the `iw` and `i(` situation work correctly.

Something I'm not sure:
- There are two `message` forms for debug use (I guess). I think we should clean them up before publish.
- I'm not familiar with the `filter-buffer-substring` function, but from its document I think it's designed for some "filtering" case. The `buffer-substring-no-properties` function may be better choice in our case.

**Comment by talwrii** [comment]
>  many edge cases to make the iw and i( situation work correctly.

Oops, I meant `aw` and `a(`, these pretty much do the correct thing in `2c87b8a` anyway

> filter-buffer-substring

This was taken from `evil-yank-characters` in `evil.el`, so I assumed it was the correct approach. But looking at the documentation:

```
filter-buffer-substring is a compiled Lisp function in `simple.el'.

(filter-buffer-substring BEG END &optional DELETE)

Return the buffer substring between BEG and END, after filtering.
If DELETE is non-nil, delete the text between BEG and END from the buffer.

This calls the function that `filter-buffer-substring-function' specifies
(passing the same three arguments that it received) to do the work,
and returns whatever it does.  The default function does no filtering,
unless a hook has been set.

Use `filter-buffer-substring' instead of `buffer-substring',
`buffer-substring-no-properties', or `delete-and-extract-region' when
you want to allow filtering to take place.  For example, major or minor
modes can use `filter-buffer-substring-function' to extract characters
that are special to a buffer, and should not be copied into other buffers.

```
`buffer-substring(-no-properties)?` seems line a better choice.

Looking inside evil itself:
```
grep -I -h -E -o 'filter-buffer-substring|buffer-substring\w*'  -r ~/.emacs.d/elpa/evil-20150619.1252  | sort | uniq -c 
     15 buffer-substring
      3 filter-buffer-substring
```

`buffer-substring` seems most commonly used. So I think I'll just retain the formatting.

**Comment by Dewdrops** [comment]
Merged. Thx!

**Comment by Dewdrops** [comment]
I've added you as a collaborator of this repo. Please open a new branch for any new feature planned.

**Pull request merged**
